name: Benchmark on PR

on:
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2
        with:
          fetch-depth: 0s

      - name: mainブランチの変更を取り込む
        run: |
          git fetch origin main
          git merge origin/main

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 既存のresults.jsonを取得
        run: |
          if [ -f results.json ]; then
            echo "Existing results.json found, copying..."
          else
            echo "No existing results.json, creating a new one."
            echo '{}' > results.json
          fi

      - name: 依存パッケージのインストール
        run: |
          npm install
          npm install benchmark

      - name: 実行速度の計測
        env:
          USER_NAME: ${{ github.event.pull_request.user.login }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: node benchmark.js

      - name: GitHub Pagesに結果をデプロイ
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
