name: Benchmark and Upload

on:
  pull_request:
    branches:
      - '**'

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run benchmark
        env:
          USER_NAME: ${{ github.actor }}
          GITHUB_REF_NAME: ${{ github.head_ref }}
        run: node benchmark.js

      - name: Generate ranking page
        run: node generateRankingPage.js

      - name: Upload results to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 cp results.json s3://${{ secrets.S3_BUCKET_NAME }}/results.json
          aws s3 cp ranking.html s3://${{ secrets.S3_BUCKET_NAME }}/ranking.html \
            --content-type text/html
