name: Deploy Benchmark Results to Pages

on:
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 依存パッケージのインストール
        run: npm install

      - name: ベンチマークを実行
        env:
          USER_NAME: ${{ github.event.pull_request.user.login }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: node benchmark.js

      - name: 既存のresults.jsonをダウンロード
        run: |
          if [ -f results.json ]; then
            echo "Using existing results.json"
          else
            echo '{}' > results.json
          fi

      - name: results.jsonの統合
        run: node merge-results.js

      - name: 結果をGitHub Pagesにデプロイ
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
