name: Benchmark and Upload

on:
  pull_request:
    branches:
      - '**'

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run benchmark
        if: success()
        env:
          USER_NAME: ${{ github.actor }}
          GITHUB_REF_NAME: ${{ github.head_ref }}
        run: |
            node benchmark.js > result.json

      - name: Upload benchmark result
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws dynamodb put-item \
            --table-name Benchmarks \
            --item file://result.json
